name: Deploy

on:
  push:
    branches: "master"

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./projet/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Coverage
        run: npm run coverage
      
      - name: Build
        run: npm run build

      - name: Upload error report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: ./coverage.json